{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "24946c52-2c73-44f8-a886-dfa71990128a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6097.35it/s]\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Hugging Face token:  ········\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-08-03 14:12:24.787 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.953 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\vasur\\anaconda3\\envs\\env_langchain1\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-08-03 14:12:24.953 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.953 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.968 Session state does not function when running a script without `streamlit run`\n",
      "2026-08-03 14:12:24.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-03 14:12:24.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# =========================\n",
    "# IMPORTS\n",
    "# =========================\n",
    "\n",
    "import os\n",
    "import streamlit as st\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_chroma import Chroma\n",
    "from langchain_openai import ChatOpenAI\n",
    "from langchain_core.prompts import ChatPromptTemplate\n",
    "\n",
    "from langchain_classic.chains import create_retrieval_chain\n",
    "from langchain_classic.chains.combine_documents import create_stuff_documents_chain\n",
    "\n",
    "\n",
    "# =========================\n",
    "# LOAD PDF\n",
    "# =========================\n",
    "\n",
    "loader = PyPDFLoader(\"yolov9_paper.pdf\")\n",
    "\n",
    "data = loader.load()\n",
    "\n",
    "\n",
    "# =========================\n",
    "# SPLIT DATA\n",
    "# =========================\n",
    "\n",
    "text_splitter = RecursiveCharacterTextSplitter(\n",
    "    chunk_size=1000,\n",
    "    chunk_overlap=200\n",
    ")\n",
    "\n",
    "docs = text_splitter.split_documents(data)\n",
    "\n",
    "\n",
    "# =========================\n",
    "# EMBEDDINGS\n",
    "# =========================\n",
    "\n",
    "embeddings = HuggingFaceEmbeddings(\n",
    "    model_name=\"sentence-transformers/all-mpnet-base-v2\"\n",
    ")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# VECTOR DATABASE\n",
    "# =========================\n",
    "\n",
    "vectorstore = Chroma.from_documents(\n",
    "    documents=docs,\n",
    "    embedding=embeddings,\n",
    "    persist_directory=\"./chroma_db\"\n",
    ")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# RETRIEVER\n",
    "# =========================\n",
    "\n",
    "retriever = vectorstore.as_retriever(\n",
    "    search_type=\"similarity\",\n",
    "    search_kwargs={\"k\": 5}\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "# =========================\n",
    "# LLM\n",
    "# =========================\n",
    "\n",
    "import os\n",
    "from getpass import getpass\n",
    "\n",
    "os.environ[\"HF_TOKEN\"] = getpass(\"Enter Hugging Face token: \")\n",
    "\n",
    "llm = ChatOpenAI(\n",
    "    model=\"openai/gpt-oss-120b\",\n",
    "    api_key=os.environ[\"HF_TOKEN\"],\n",
    "    base_url=\"https://router.huggingface.co/v1\",\n",
    "    temperature=0.1,\n",
    "    max_tokens=400\n",
    ")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# PROMPT\n",
    "# =========================\n",
    "\n",
    "system_prompt = (\n",
    "    \"You are an assistant for question-answering tasks. \"\n",
    "    \"Use the following pieces of retrieved context to answer the question. \"\n",
    "    \"If you don't know the answer, say that you don't know. \"\n",
    "    \"Use three sentences maximum and keep the answer concise. \"\n",
    "    \"\\n\\n\"\n",
    "    \"{context}\"\n",
    ")\n",
    "\n",
    "prompt = ChatPromptTemplate.from_messages(\n",
    "    [\n",
    "        (\"system\", system_prompt),\n",
    "        (\"human\", \"{input}\"),\n",
    "    ]\n",
    ")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# RAG CHAIN\n",
    "# =========================\n",
    "\n",
    "question_answer_chain = create_stuff_documents_chain(\n",
    "    llm,\n",
    "    prompt\n",
    ")\n",
    "\n",
    "rag_chain = create_retrieval_chain(\n",
    "    retriever,\n",
    "    question_answer_chain\n",
    ")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# STREAMLIT\n",
    "# =========================\n",
    "\n",
    "st.title(\"YOLOv9 RAG Application\")\n",
    "\n",
    "question = st.text_input(\n",
    "    \"Ask a question about YOLOv9\"\n",
    ")\n",
    "\n",
    "if question:\n",
    "\n",
    "    response = rag_chain.invoke(\n",
    "        {\"input\": question}\n",
    "    )\n",
    "\n",
    "    st.write(response[\"answer\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0a84ee0-58fc-4ec0-8409-a650ee0071fc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (env_langchain1)",
   "language": "python",
   "name": "env_langchain1"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
